// This file is automatically generated. Do not edit it directly.
// Regenerated from the live Supabase project (xatlqnbrvgukuqewsxux) on 2026-06-16.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "12.2.3 (519615d)"
  }
  public: {
    Tables: {
      app_admins: {
        Row: {
          created_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          user_id?: string
        }
        Relationships: []
      }
      completion_requests: {
        Row: {
          created_at: string
          deal_id: string
          id: string
          request_message: string | null
          requester_id: string
          requester_type: string
          responded_at: string | null
          responded_by: string | null
          response_message: string | null
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          deal_id: string
          id?: string
          request_message?: string | null
          requester_id: string
          requester_type: string
          responded_at?: string | null
          responded_by?: string | null
          response_message?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          deal_id?: string
          id?: string
          request_message?: string | null
          requester_id?: string
          requester_type?: string
          responded_at?: string | null
          responded_by?: string | null
          response_message?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "completion_requests_deal_id_fkey"
            columns: ["deal_id"]
            isOneToOne: false
            referencedRelation: "deals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "completion_requests_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "completion_requests_responded_by_fkey"
            columns: ["responded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          client_archived: boolean
          client_id: string
          client_unread_count: number | null
          created_at: string
          deal_id: string | null
          id: string
          job_id: string
          proposal_id: string | null
          provider_archived: boolean
          provider_id: string
          provider_unread_count: number | null
          status: string
          updated_at: string
        }
        Insert: {
          client_archived?: boolean
          client_id: string
          client_unread_count?: number | null
          created_at?: string
          deal_id?: string | null
          id?: string
          job_id: string
          proposal_id?: string | null
          provider_archived?: boolean
          provider_id: string
          provider_unread_count?: number | null
          status?: string
          updated_at?: string
        }
        Update: {
          client_archived?: boolean
          client_id?: string
          client_unread_count?: number | null
          created_at?: string
          deal_id?: string | null
          id?: string
          job_id?: string
          proposal_id?: string | null
          provider_archived?: boolean
          provider_id?: string
          provider_unread_count?: number | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversations_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_deal_id_fkey"
            columns: ["deal_id"]
            isOneToOne: false
            referencedRelation: "deals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_proposal_id_fkey"
            columns: ["proposal_id"]
            isOneToOne: false
            referencedRelation: "proposals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_provider_id_fkey"
            columns: ["provider_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      deal_disputes: {
        Row: {
          created_at: string
          deal_id: string
          id: string
          raised_by: string
          reason: string | null
          resolution: Json | null
          resolved_at: string | null
          resolved_by: string | null
          status: string
        }
        Insert: {
          created_at?: string
          deal_id: string
          id?: string
          raised_by: string
          reason?: string | null
          resolution?: Json | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
        }
        Update: {
          created_at?: string
          deal_id?: string
          id?: string
          raised_by?: string
          reason?: string | null
          resolution?: Json | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "deal_disputes_deal_id_fkey"
            columns: ["deal_id"]
            isOneToOne: false
            referencedRelation: "deals"
            referencedColumns: ["id"]
          },
        ]
      }
      deal_offers: {
        Row: {
          amount: number
          client_id: string
          conversation_id: string
          created_at: string
          id: string
          job_id: string
          provider_id: string
          responded_at: string | null
          status: string
          terms: string | null
          timeline: string | null
        }
        Insert: {
          amount: number
          client_id: string
          conversation_id: string
          created_at?: string
          id?: string
          job_id: string
          provider_id: string
          responded_at?: string | null
          status?: string
          terms?: string | null
          timeline?: string | null
        }
        Update: {
          amount?: number
          client_id?: string
          conversation_id?: string
          created_at?: string
          id?: string
          job_id?: string
          provider_id?: string
          responded_at?: string | null
          status?: string
          terms?: string | null
          timeline?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "deal_offers_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deal_offers_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversation_details"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deal_offers_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deal_offers_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations_with_latest_message"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deal_offers_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deal_offers_provider_id_fkey"
            columns: ["provider_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      deals: {
        Row: {
          agreed_amount: number
          agreed_terms: string | null
          client_completion_requested: boolean | null
          client_completion_requested_at: string | null
          client_id: string
          completed_at: string | null
          completion_status: string | null
          conversation_id: string | null
          created_at: string
          deal_offer_id: string | null
          id: string
          job_id: string
          proposal_id: string | null
          provider_completion_requested: boolean | null
          provider_completion_requested_at: string | null
          provider_id: string
          status: string
          timeline: string | null
        }
        Insert: {
          agreed_amount: number
          agreed_terms?: string | null
          client_completion_requested?: boolean | null
          client_completion_requested_at?: string | null
          client_id: string
          completed_at?: string | null
          completion_status?: string | null
          conversation_id?: string | null
          created_at?: string
          deal_offer_id?: string | null
          id?: string
          job_id: string
          proposal_id?: string | null
          provider_completion_requested?: boolean | null
          provider_completion_requested_at?: string | null
          provider_id: string
          status?: string
          timeline?: string | null
        }
        Update: {
          agreed_amount?: number
          agreed_terms?: string | null
          client_completion_requested?: boolean | null
          client_completion_requested_at?: string | null
          client_id?: string
          completed_at?: string | null
          completion_status?: string | null
          conversation_id?: string | null
          created_at?: string
          deal_offer_id?: string | null
          id?: string
          job_id?: string
          proposal_id?: string | null
          provider_completion_requested?: boolean | null
          provider_completion_requested_at?: string | null
          provider_id?: string
          status?: string
          timeline?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "deals_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deals_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deals_proposal_id_fkey"
            columns: ["proposal_id"]
            isOneToOne: false
            referencedRelation: "proposals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deals_provider_id_fkey"
            columns: ["provider_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      escrow_events: {
        Row: {
          actor: string | null
          created_at: string
          escrow_id: string
          from_state: Database["public"]["Enums"]["escrow_state"] | null
          id: string
          meta: Json | null
          to_state: Database["public"]["Enums"]["escrow_state"]
        }
        Insert: {
          actor?: string | null
          created_at?: string
          escrow_id: string
          from_state?: Database["public"]["Enums"]["escrow_state"] | null
          id?: string
          meta?: Json | null
          to_state: Database["public"]["Enums"]["escrow_state"]
        }
        Update: {
          actor?: string | null
          created_at?: string
          escrow_id?: string
          from_state?: Database["public"]["Enums"]["escrow_state"] | null
          id?: string
          meta?: Json | null
          to_state?: Database["public"]["Enums"]["escrow_state"]
        }
        Relationships: [
          {
            foreignKeyName: "escrow_events_escrow_id_fkey"
            columns: ["escrow_id"]
            isOneToOne: false
            referencedRelation: "escrow_transactions"
            referencedColumns: ["id"]
          },
        ]
      }
      escrow_transactions: {
        Row: {
          amount: number
          client_id: string
          collection_payment_id: string | null
          collection_trx_id: string | null
          created_at: string
          currency: string
          deal_id: string
          deal_offer_id: string | null
          held_at: string | null
          id: string
          notes: string | null
          paid_out_at: string | null
          paid_out_by: string | null
          payout_amount: number | null
          payout_trx_id: string | null
          platform_fee: number
          provider_amount: number
          provider_id: string
          provider_msisdn: string | null
          refund_amount: number | null
          refund_trx_id: string | null
          refunded_at: string | null
          released_at: string | null
          resolved_at: string | null
          state: Database["public"]["Enums"]["escrow_state"]
          updated_at: string
        }
        Insert: {
          amount: number
          client_id: string
          collection_payment_id?: string | null
          collection_trx_id?: string | null
          created_at?: string
          currency?: string
          deal_id: string
          deal_offer_id?: string | null
          held_at?: string | null
          id?: string
          notes?: string | null
          paid_out_at?: string | null
          paid_out_by?: string | null
          payout_amount?: number | null
          payout_trx_id?: string | null
          platform_fee?: number
          provider_amount: number
          provider_id: string
          provider_msisdn?: string | null
          refund_amount?: number | null
          refund_trx_id?: string | null
          refunded_at?: string | null
          released_at?: string | null
          resolved_at?: string | null
          state?: Database["public"]["Enums"]["escrow_state"]
          updated_at?: string
        }
        Update: {
          amount?: number
          client_id?: string
          collection_payment_id?: string | null
          collection_trx_id?: string | null
          created_at?: string
          currency?: string
          deal_id?: string
          deal_offer_id?: string | null
          held_at?: string | null
          id?: string
          notes?: string | null
          paid_out_at?: string | null
          paid_out_by?: string | null
          payout_amount?: number | null
          payout_trx_id?: string | null
          platform_fee?: number
          provider_amount?: number
          provider_id?: string
          provider_msisdn?: string | null
          refund_amount?: number | null
          refund_trx_id?: string | null
          refunded_at?: string | null
          released_at?: string | null
          resolved_at?: string | null
          state?: Database["public"]["Enums"]["escrow_state"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "escrow_transactions_deal_id_fkey"
            columns: ["deal_id"]
            isOneToOne: true
            referencedRelation: "deals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "escrow_transactions_deal_offer_id_fkey"
            columns: ["deal_offer_id"]
            isOneToOne: false
            referencedRelation: "deal_offers"
            referencedColumns: ["id"]
          },
        ]
      }
      job_bookmarks: {
        Row: {
          bookmarked_at: string
          id: string
          job_id: string
          user_id: string
        }
        Insert: {
          bookmarked_at?: string
          id?: string
          job_id: string
          user_id: string
        }
        Update: {
          bookmarked_at?: string
          id?: string
          job_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_bookmarks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      job_interests: {
        Row: {
          actioned_at: string | null
          created_at: string
          id: string
          job_id: string
          message: string | null
          provider_id: string
          read: boolean | null
          read_at: string | null
          status: string | null
        }
        Insert: {
          actioned_at?: string | null
          created_at?: string
          id?: string
          job_id: string
          message?: string | null
          provider_id: string
          read?: boolean | null
          read_at?: string | null
          status?: string | null
        }
        Update: {
          actioned_at?: string | null
          created_at?: string
          id?: string
          job_id?: string
          message?: string | null
          provider_id?: string
          read?: boolean | null
          read_at?: string | null
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "job_interests_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      job_views: {
        Row: {
          created_at: string
          id: string
          job_id: string
          user_id: string
          viewed_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          job_id: string
          user_id: string
          viewed_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          job_id?: string
          user_id?: string
          viewed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_views_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          budget: number
          category: string
          client_id: string
          created_at: string
          description: string
          id: string
          location: string
          media_urls: Json | null
          status: string | null
          title: string
          updated_at: string
          urgent: boolean | null
        }
        Insert: {
          budget: number
          category: string
          client_id: string
          created_at?: string
          description: string
          id?: string
          location: string
          media_urls?: Json | null
          status?: string | null
          title: string
          updated_at?: string
          urgent?: boolean | null
        }
        Update: {
          budget?: number
          category?: string
          client_id?: string
          created_at?: string
          description?: string
          id?: string
          location?: string
          media_urls?: Json | null
          status?: string | null
          title?: string
          updated_at?: string
          urgent?: boolean | null
        }
        Relationships: []
      }
      messages: {
        Row: {
          attachment_url: string | null
          content: string
          conversation_id: string
          created_at: string
          deal_offer_id: string | null
          id: string
          message_type: string
          negotiation_data: Json | null
          original_proposal_id: string | null
          read_at: string | null
          sender_id: string
        }
        Insert: {
          attachment_url?: string | null
          content: string
          conversation_id: string
          created_at?: string
          deal_offer_id?: string | null
          id?: string
          message_type?: string
          negotiation_data?: Json | null
          original_proposal_id?: string | null
          read_at?: string | null
          sender_id: string
        }
        Update: {
          attachment_url?: string | null
          content?: string
          conversation_id?: string
          created_at?: string
          deal_offer_id?: string | null
          id?: string
          message_type?: string
          negotiation_data?: Json | null
          original_proposal_id?: string | null
          read_at?: string | null
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversation_details"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations_with_latest_message"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_deal_offer_id_fkey"
            columns: ["deal_offer_id"]
            isOneToOne: false
            referencedRelation: "deal_offers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_original_proposal_id_fkey"
            columns: ["original_proposal_id"]
            isOneToOne: false
            referencedRelation: "proposals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          action_data: Json | null
          actioned_at: string | null
          archived_at: string | null
          avatar_url: string | null
          completion_request_id: string | null
          created_at: string
          deal_offer_id: string | null
          from_user_id: string | null
          grouped_date: string | null
          id: string
          interaction_type:
            | Database["public"]["Enums"]["interaction_type"]
            | null
          job_id: string | null
          message: string | null
          notification_state:
            | Database["public"]["Enums"]["notification_state"]
            | null
          offer_data: Json | null
          priority: Database["public"]["Enums"]["notification_priority"] | null
          read: boolean
          read_at: string | null
          related_job_id: string | null
          related_proposal_id: string | null
          status: string | null
          title: string | null
          to_user_id: string | null
          type: string | null
          user_id: string | null
        }
        Insert: {
          action_data?: Json | null
          actioned_at?: string | null
          archived_at?: string | null
          avatar_url?: string | null
          completion_request_id?: string | null
          created_at?: string
          deal_offer_id?: string | null
          from_user_id?: string | null
          grouped_date?: string | null
          id?: string
          interaction_type?:
            | Database["public"]["Enums"]["interaction_type"]
            | null
          job_id?: string | null
          message?: string | null
          notification_state?:
            | Database["public"]["Enums"]["notification_state"]
            | null
          offer_data?: Json | null
          priority?: Database["public"]["Enums"]["notification_priority"] | null
          read?: boolean
          read_at?: string | null
          related_job_id?: string | null
          related_proposal_id?: string | null
          status?: string | null
          title?: string | null
          to_user_id?: string | null
          type?: string | null
          user_id?: string | null
        }
        Update: {
          action_data?: Json | null
          actioned_at?: string | null
          archived_at?: string | null
          avatar_url?: string | null
          completion_request_id?: string | null
          created_at?: string
          deal_offer_id?: string | null
          from_user_id?: string | null
          grouped_date?: string | null
          id?: string
          interaction_type?:
            | Database["public"]["Enums"]["interaction_type"]
            | null
          job_id?: string | null
          message?: string | null
          notification_state?:
            | Database["public"]["Enums"]["notification_state"]
            | null
          offer_data?: Json | null
          priority?: Database["public"]["Enums"]["notification_priority"] | null
          read?: boolean
          read_at?: string | null
          related_job_id?: string | null
          related_proposal_id?: string | null
          status?: string | null
          title?: string | null
          to_user_id?: string | null
          type?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_completion_request_id_fkey"
            columns: ["completion_request_id"]
            isOneToOne: false
            referencedRelation: "completion_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_from_user_id_fkey"
            columns: ["from_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_from_user_id_fkey_profiles"
            columns: ["from_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_to_user_id_fkey"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_to_user_id_fkey_profiles"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          average_response_time_minutes: number | null
          bio: string | null
          created_at: string
          device_token: string | null
          email: string | null
          experience_years: number | null
          favorite_categories: string[] | null
          full_name: string | null
          hourly_rate: number | null
          id: string
          is_online: boolean | null
          is_service_provider: boolean | null
          last_push_sent_at: string | null
          last_seen_at: string | null
          location: string | null
          phone: string | null
          profession: string | null
          push_enabled: boolean | null
          tagline: string | null
          team_hours_label: string | null
          team_rate: number | null
          updated_at: string
          user_type: string | null
          website: string | null
        }
        Insert: {
          avatar_url?: string | null
          average_response_time_minutes?: number | null
          bio?: string | null
          created_at?: string
          device_token?: string | null
          email?: string | null
          experience_years?: number | null
          favorite_categories?: string[] | null
          full_name?: string | null
          hourly_rate?: number | null
          id: string
          is_online?: boolean | null
          is_service_provider?: boolean | null
          last_push_sent_at?: string | null
          last_seen_at?: string | null
          location?: string | null
          phone?: string | null
          profession?: string | null
          push_enabled?: boolean | null
          tagline?: string | null
          team_hours_label?: string | null
          team_rate?: number | null
          updated_at?: string
          user_type?: string | null
          website?: string | null
        }
        Update: {
          avatar_url?: string | null
          average_response_time_minutes?: number | null
          bio?: string | null
          created_at?: string
          device_token?: string | null
          email?: string | null
          experience_years?: number | null
          favorite_categories?: string[] | null
          full_name?: string | null
          hourly_rate?: number | null
          id?: string
          is_online?: boolean | null
          is_service_provider?: boolean | null
          last_push_sent_at?: string | null
          last_seen_at?: string | null
          location?: string | null
          phone?: string | null
          profession?: string | null
          push_enabled?: boolean | null
          tagline?: string | null
          team_hours_label?: string | null
          team_rate?: number | null
          updated_at?: string
          user_type?: string | null
          website?: string | null
        }
        Relationships: []
      }
      proposals: {
        Row: {
          amount: number
          created_at: string
          id: string
          job_id: string
          message: string | null
          provider_id: string
          status: string
          updated_at: string
        }
        Insert: {
          amount: number
          created_at?: string
          id?: string
          job_id: string
          message?: string | null
          provider_id: string
          status?: string
          updated_at?: string
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          job_id?: string
          message?: string | null
          provider_id?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "proposals_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "proposals_provider_id_fkey"
            columns: ["provider_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      provider_payout_accounts: {
        Row: {
          bkash_number: string
          updated_at: string
          user_id: string
        }
        Insert: {
          bkash_number: string
          updated_at?: string
          user_id: string
        }
        Update: {
          bkash_number?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "provider_payout_accounts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      public_profiles: {
        Row: {
          avatar_url: string | null
          average_response_time_minutes: number | null
          avg_job_value: number | null
          avg_rating: number | null
          bio: string | null
          completed_jobs: number | null
          created_at: string | null
          experience_years: number | null
          full_name: string | null
          hourly_rate: number | null
          id: string
          is_online: boolean | null
          is_service_provider: boolean | null
          last_seen_at: string | null
          last_updated: string | null
          location: string | null
          profession: string | null
          review_count: number | null
          service_categories: Json | null
          tagline: string | null
          team_hours_label: string | null
          team_rate: number | null
          total_earnings: number | null
          trust_level: string | null
          website: string | null
        }
        Insert: {
          avatar_url?: string | null
          average_response_time_minutes?: number | null
          avg_job_value?: number | null
          avg_rating?: number | null
          bio?: string | null
          completed_jobs?: number | null
          created_at?: string | null
          experience_years?: number | null
          full_name?: string | null
          hourly_rate?: number | null
          id: string
          is_online?: boolean | null
          is_service_provider?: boolean | null
          last_seen_at?: string | null
          last_updated?: string | null
          location?: string | null
          profession?: string | null
          review_count?: number | null
          service_categories?: Json | null
          tagline?: string | null
          team_hours_label?: string | null
          team_rate?: number | null
          total_earnings?: number | null
          trust_level?: string | null
          website?: string | null
        }
        Update: {
          avatar_url?: string | null
          average_response_time_minutes?: number | null
          avg_job_value?: number | null
          avg_rating?: number | null
          bio?: string | null
          completed_jobs?: number | null
          created_at?: string | null
          experience_years?: number | null
          full_name?: string | null
          hourly_rate?: number | null
          id?: string
          is_online?: boolean | null
          is_service_provider?: boolean | null
          last_seen_at?: string | null
          last_updated?: string | null
          location?: string | null
          profession?: string | null
          review_count?: number | null
          service_categories?: Json | null
          tagline?: string | null
          team_hours_label?: string | null
          team_rate?: number | null
          total_earnings?: number | null
          trust_level?: string | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "public_profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      push_notifications: {
        Row: {
          body: string
          created_at: string | null
          data: Json | null
          delivery_status: string | null
          device_token: string
          error_message: string | null
          id: string
          notification_type: string
          sent_at: string | null
          title: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string | null
          data?: Json | null
          delivery_status?: string | null
          device_token: string
          error_message?: string | null
          id?: string
          notification_type: string
          sent_at?: string | null
          title: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string | null
          data?: Json | null
          delivery_status?: string | null
          device_token?: string
          error_message?: string | null
          id?: string
          notification_type?: string
          sent_at?: string | null
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          comment: string | null
          created_at: string
          id: string
          job_id: string
          rating: number
          reviewed_id: string
          reviewer_id: string
        }
        Insert: {
          comment?: string | null
          created_at?: string
          id?: string
          job_id: string
          rating: number
          reviewed_id: string
          reviewer_id: string
        }
        Update: {
          comment?: string | null
          created_at?: string
          id?: string
          job_id?: string
          rating?: number
          reviewed_id?: string
          reviewer_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      service_categories: {
        Row: {
          created_at: string
          description: string | null
          icon: string | null
          id: string
          name: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          name: string
        }
        Update: {
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
    }
    Views: {
      conversation_details: {
        Row: {
          client_avatar: string | null
          client_id: string | null
          client_name: string | null
          created_at: string | null
          deal_id: string | null
          id: string | null
          job_budget: number | null
          job_description: string | null
          job_id: string | null
          job_title: string | null
          latest_message_content: string | null
          latest_message_sender: string | null
          latest_message_time: string | null
          proposal_id: string | null
          provider_avatar: string | null
          provider_id: string | null
          provider_name: string | null
          status: string | null
          unread_count_placeholder: number | null
          updated_at: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_deal_id_fkey"
            columns: ["deal_id"]
            isOneToOne: false
            referencedRelation: "deals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_proposal_id_fkey"
            columns: ["proposal_id"]
            isOneToOne: false
            referencedRelation: "proposals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_provider_id_fkey"
            columns: ["provider_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["latest_message_sender"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations_with_latest_message: {
        Row: {
          client_id: string | null
          client_unread_count: number | null
          created_at: string | null
          deal_id: string | null
          id: string | null
          job_id: string | null
          latest_message_content: string | null
          latest_message_created_at: string | null
          latest_message_id: string | null
          latest_message_sender_id: string | null
          latest_message_type: string | null
          proposal_id: string | null
          provider_id: string | null
          provider_unread_count: number | null
          status: string | null
          updated_at: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_deal_id_fkey"
            columns: ["deal_id"]
            isOneToOne: false
            referencedRelation: "deals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_proposal_id_fkey"
            columns: ["proposal_id"]
            isOneToOne: false
            referencedRelation: "proposals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_provider_id_fkey"
            columns: ["provider_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["latest_message_sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pending_notifications_summary: {
        Row: {
          interest_requests: number | null
          offer_requests: number | null
          pending_count: number | null
          to_user_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_to_user_id_fkey"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_to_user_id_fkey_profiles"
            columns: ["to_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      apply_for_job: {
        Args: { p_job_id: string; p_provider_id: string }
        Returns: string
      }
      cleanup_expired_cooldowns: {
        Args: { cooldown_expire_days?: number }
        Returns: Json
      }
      cleanup_interest_violations: {
        Args: { retention_days?: number }
        Returns: Json
      }
      create_notification: {
        Args: {
          p_message: string
          p_related_job_id?: string
          p_related_proposal_id?: string
          p_title: string
          p_type: string
          p_user_id: string
        }
        Returns: string
      }
      deal_open_dispute: {
        Args: { p_deal_id: string; p_reason: string }
        Returns: {
          created_at: string
          deal_id: string
          id: string
          raised_by: string
          reason: string | null
          resolution: Json | null
          resolved_at: string | null
          resolved_by: string | null
          status: string
        }
        SetofOptions: {
          from: "*"
          to: "deal_disputes"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      escrow_finalize_offer: {
        Args: {
          p_deal_offer_id: string
          p_payment_id: string
          p_trx_id: string
        }
        Returns: {
          amount: number
          client_id: string
          collection_payment_id: string | null
          collection_trx_id: string | null
          created_at: string
          currency: string
          deal_id: string
          deal_offer_id: string | null
          held_at: string | null
          id: string
          notes: string | null
          paid_out_at: string | null
          paid_out_by: string | null
          payout_amount: number | null
          payout_trx_id: string | null
          platform_fee: number
          provider_amount: number
          provider_id: string
          provider_msisdn: string | null
          refund_amount: number | null
          refund_trx_id: string | null
          refunded_at: string | null
          released_at: string | null
          resolved_at: string | null
          state: Database["public"]["Enums"]["escrow_state"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "escrow_transactions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      escrow_mark_collected: {
        Args: { p_deal_id: string; p_payment_id: string; p_trx_id: string }
        Returns: {
          amount: number
          client_id: string
          collection_payment_id: string | null
          collection_trx_id: string | null
          created_at: string
          currency: string
          deal_id: string
          deal_offer_id: string | null
          held_at: string | null
          id: string
          notes: string | null
          paid_out_at: string | null
          paid_out_by: string | null
          payout_amount: number | null
          payout_trx_id: string | null
          platform_fee: number
          provider_amount: number
          provider_id: string
          provider_msisdn: string | null
          refund_amount: number | null
          refund_trx_id: string | null
          refunded_at: string | null
          released_at: string | null
          resolved_at: string | null
          state: Database["public"]["Enums"]["escrow_state"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "escrow_transactions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      escrow_mark_paid_out: {
        Args: { p_escrow_id: string; p_notes?: string; p_trx_id?: string }
        Returns: {
          amount: number
          client_id: string
          collection_payment_id: string | null
          collection_trx_id: string | null
          created_at: string
          currency: string
          deal_id: string
          deal_offer_id: string | null
          held_at: string | null
          id: string
          notes: string | null
          paid_out_at: string | null
          paid_out_by: string | null
          payout_amount: number | null
          payout_trx_id: string | null
          platform_fee: number
          provider_amount: number
          provider_id: string
          provider_msisdn: string | null
          refund_amount: number | null
          refund_trx_id: string | null
          refunded_at: string | null
          released_at: string | null
          resolved_at: string | null
          state: Database["public"]["Enums"]["escrow_state"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "escrow_transactions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      escrow_mark_refunded: {
        Args: { p_escrow_id: string; p_notes?: string }
        Returns: {
          amount: number
          client_id: string
          collection_payment_id: string | null
          collection_trx_id: string | null
          created_at: string
          currency: string
          deal_id: string
          deal_offer_id: string | null
          held_at: string | null
          id: string
          notes: string | null
          paid_out_at: string | null
          paid_out_by: string | null
          payout_amount: number | null
          payout_trx_id: string | null
          platform_fee: number
          provider_amount: number
          provider_id: string
          provider_msisdn: string | null
          refund_amount: number | null
          refund_trx_id: string | null
          refunded_at: string | null
          released_at: string | null
          resolved_at: string | null
          state: Database["public"]["Enums"]["escrow_state"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "escrow_transactions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      escrow_service_mark_paid_out: {
        Args: { p_escrow_id: string; p_notes?: string; p_trx_id?: string }
        Returns: {
          amount: number
          client_id: string
          collection_payment_id: string | null
          collection_trx_id: string | null
          created_at: string
          currency: string
          deal_id: string
          deal_offer_id: string | null
          held_at: string | null
          id: string
          notes: string | null
          paid_out_at: string | null
          paid_out_by: string | null
          payout_amount: number | null
          payout_trx_id: string | null
          platform_fee: number
          provider_amount: number
          provider_id: string
          provider_msisdn: string | null
          refund_amount: number | null
          refund_trx_id: string | null
          refunded_at: string | null
          released_at: string | null
          resolved_at: string | null
          state: Database["public"]["Enums"]["escrow_state"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "escrow_transactions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      escrow_service_resolve_dispute: {
        Args: {
          p_escrow_id: string
          p_notes?: string
          p_payout_amount: number
          p_payout_trx?: string
          p_refund_amount: number
          p_refund_trx?: string
        }
        Returns: {
          amount: number
          client_id: string
          collection_payment_id: string | null
          collection_trx_id: string | null
          created_at: string
          currency: string
          deal_id: string
          deal_offer_id: string | null
          held_at: string | null
          id: string
          notes: string | null
          paid_out_at: string | null
          paid_out_by: string | null
          payout_amount: number | null
          payout_trx_id: string | null
          platform_fee: number
          provider_amount: number
          provider_id: string
          provider_msisdn: string | null
          refund_amount: number | null
          refund_trx_id: string | null
          refunded_at: string | null
          released_at: string | null
          resolved_at: string | null
          state: Database["public"]["Enums"]["escrow_state"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "escrow_transactions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      get_cooldown_cleanup_stats: { Args: never; Returns: Json }
      get_deal_count: {
        Args: { job_uuid: string; provider_uuid: string }
        Returns: number
      }
      get_interest_status: {
        Args: { p_job_id: string; p_provider_id: string }
        Returns: Json
      }
      get_latest_messages_for_conversations: {
        Args: { conversation_ids: string[] }
        Returns: {
          attachment_url: string
          content: string
          conversation_id: string
          created_at: string
          id: string
          message_type: string
          negotiation_data: Json
          original_proposal_id: string
          read_at: string
          sender_id: string
        }[]
      }
      get_pending_notification_count: {
        Args: { user_uuid: string }
        Returns: number
      }
      get_total_unread_count: { Args: { user_id: string }; Returns: number }
      get_unread_counts_for_conversations: {
        Args: { conversation_ids: string[]; user_id: string }
        Returns: {
          conversation_id: string
          unread_count: number
        }[]
      }
      get_user_conversations_optimized: {
        Args: { user_id: string }
        Returns: {
          client_avatar: string
          client_id: string
          client_name: string
          created_at: string
          id: string
          job_budget: number
          job_description: string
          job_id: string
          job_title: string
          latest_message_content: string
          latest_message_sender: string
          latest_message_time: string
          provider_avatar: string
          provider_id: string
          provider_name: string
          status: string
          unread_count: number
          updated_at: string
        }[]
      }
      get_user_dashboard_data: {
        Args: { user_id: string }
        Returns: {
          active_deals_count: number
          average_rating: number
          completed_deals_count: number
          pending_completion_requests: number
          recent_deals: Json
          total_earnings: number
          total_spent: number
          user_type: string
        }[]
      }
      get_user_total_unread_count: {
        Args: { user_uuid: string }
        Returns: number
      }
      is_admin: { Args: { p_uid: string }; Returns: boolean }
      perform_cooldown_maintenance: {
        Args: {
          cooldown_expire_days?: number
          violation_retention_days?: number
        }
        Returns: Json
      }
      refresh_all_public_profiles: { Args: never; Returns: undefined }
      refresh_public_profile: { Args: { user_id: string }; Returns: undefined }
      send_push_notification: {
        Args: {
          p_body: string
          p_data?: Json
          p_notification_type?: string
          p_title: string
          p_user_id: string
        }
        Returns: undefined
      }
      show_interest_in_job:
        | { Args: { p_job_id: string }; Returns: Json }
        | { Args: { p_job_id: string; p_message?: string }; Returns: Json }
      track_job_view: {
        Args: { p_job_id: string; p_user_id: string }
        Returns: undefined
      }
      validate_interest_attempt: {
        Args: { p_job_id: string; p_provider_id: string }
        Returns: Json
      }
    }
    Enums: {
      escrow_state:
        | "pending"
        | "held"
        | "released"
        | "paid_out"
        | "refunded"
        | "failed"
        | "resolved"
      interaction_type: "interactive" | "informational"
      notification_priority: "high" | "normal" | "low"
      notification_state: "unread" | "read" | "archived"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      escrow_state: [
        "pending",
        "held",
        "released",
        "paid_out",
        "refunded",
        "failed",
        "resolved",
      ],
      interaction_type: ["interactive", "informational"],
      notification_priority: ["high", "normal", "low"],
      notification_state: ["unread", "read", "archived"],
    },
  },
} as const
